**2. Preparar el entorno y cargar el dataset

In [1]:
# Importar librerías necesarias
import os
import requests
import pandas as pd
import pathlib

**2.1 Cargar el dataset

In [2]:
# Define el directorio donde se guardarán los datos
_data_root = './data/covertype'
# Define la ruta completa del archivo de entrenamiento
_data_filepath = os.path.join(_data_root, 'covertype_train.csv')

In [3]:
# Crea el directorio si no existe
os.makedirs(_data_root, exist_ok=True)

In [4]:
# Si el archivo no existe, se descarga desde la URL (reemplaza la URL con la que corresponda)
if not os.path.isfile(_data_filepath):
    #https://archive.ics.uci.edu/ml/machine-learning-databases/covtype/ 
    url = "https://docs.google.com/uc?export=download&id=1lVF1BCWLH4eXXV_YOJzjR7xZjj-wAGj9"  # Ajusta este enlace según tu necesidad
    r = requests.get(url, allow_redirects=True, stream=True)
    with open(_data_filepath, 'wb') as f:
        f.write(r.content)
    print("Dataset descargado.")
else:
    print("El dataset ya existe.")

El dataset ya existe.

In [5]:
# Cargar el dataset en un DataFrame
df = pd.read_csv(_data_filepath)
print("Dimensiones del dataset:", df.shape)
# Mostrar las primeras 5 filas
df.head()

Dimensiones del dataset: (116203, 13)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area,Soil_Type,Cover_Type
0,2991,119,7,67,11,1015,233,234,133,1570,Commanche,C7202,1
1,2876,3,18,485,71,2495,192,202,144,1557,Commanche,C7757,1
2,3171,315,2,277,9,4374,213,237,162,1052,Rawah,C7745,0
3,3087,342,13,190,31,4774,193,221,166,752,Rawah,C7745,0
4,2835,158,10,212,41,3596,231,242,141,3280,Rawah,C4744,1

In [6]:
# Mostrar información general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116203 entries, 0 to 116202
Data columns (total 13 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           116203 non-null  int64
 1   Aspect                              116203 non-null  int64
 2   Slope                               116203 non-null  int64
 3   Horizontal_Distance_To_Hydrology    116203 non-null  int64
 4   Vertical_Distance_To_Hydrology      116203 non-null  int64
 5   Horizontal_Distance_To_Roadways     116203 non-null  int64
 6   Hillshade_9am                       116203 non-null  int64
 7   Hillshade_Noon                      116203 non-null  int64
 8   Hillshade_3pm                       116203 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  116203 non-null  int64
 10  Wilderness_Area                     116203 non-null  object
 11  Soil_Type                           116203 non-null  object
 12  Cover_Type                          116203 non-null  int64
dtypes: int64(11), object(2)
memory usage: 11.5+ MB

**3. Selección de características

In [7]:
from dataclasses import dataclass
from typing import List
from pathlib import Path

data_root_prepro = Path("./data_prepro")
data_root_prepro.mkdir(parents=True, exist_ok=True)  # Crea el directorio si no existe

@dataclass
class DataConfig:
    target_col: str
    non_numeric_cols: List[str]
    final_df_path: Path
    
# Definir data_root_prepro y crear el directorio si es necesario
data_root_prepro = Path("./data_prepro")
data_root_prepro.mkdir(parents=True, exist_ok=True)

    
#Creating an instance with specific values
config = DataConfig(
    target_col="Cover_Type",
    non_numeric_cols=list(df.select_dtypes(include=['object']).columns),
    final_df_path= data_root_prepro / "covertype_preprocessed.csv"
)

La ejecución de la siguiente celda se omite mediante el comando %%script false --no-raise-error, ya que contiene la normalización de lso datos, un proceso que ya se realizó previamente según lo indicado en el documento.

**"Recuerde que primero debe preparar las características de entrada y de destino:"

Sin embargo, más adelante en el documento se asume que los datos conservan sus valores originales, por lo que la normalización se aplica posteriormente utilizando las herramientas de TFX.

In [8]:
%%script false --no-raise-error

from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif

# Drop non-numeric columns
df_1 = df.drop(columns=config.non_numeric_cols)

#Separate features and label
X = df_1.drop(columns=[config.target_col])
Y = df_1[config.target_col].astype('category')

#Scale data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Convert back to Dataframe with original column names
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

#Implement f_classif as score function and select the 8 best columns
selector = SelectKBest(score_func=f_classif, k=8)
selector.fit(X,y)

#Create and print a df comparing the column and the result (if its retained or not)
selected_columns_df = pd.DataFrame({
    'Column': X_scaled.columns,
    'Retain': selector.get_support()
})
selected_columns_df

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif

#Drop non-numeric columns
df_1 = df.drop(columns=config.non_numeric_cols)

#Separate features and label
X = df_1.drop(columns=[config.target_col])
y = df_1[config.target_col].astype('category')

#Implement f_classif as score function and select the 8 best columns
selector = SelectKBest(score_func=f_classif, k=8)
selector.fit(X,y)

#Select the best features using boolean mask
X_selected = X.loc[:, selector.get_support()]

#Create and print a df comparing the column and the result (if its retained or not)
selected_columns_df = pd.DataFrame({
    'Column': X.columns,
    'Retain': selector.get_support()
})
selected_columns_df

                               Column  Retain
0                           Elevation    True
1                              Aspect   False
2                               Slope    True
3    Horizontal_Distance_To_Hydrology    True
4      Vertical_Distance_To_Hydrology    True
5     Horizontal_Distance_To_Roadways    True
6                       Hillshade_9am    True
7                      Hillshade_Noon    True
8                       Hillshade_3pm   False
9  Horizontal_Distance_To_Fire_Points    True

In [10]:
# Add the target column back

final_df = X_selected.copy()
final_df[config.target_col] = y.values

#Save the updated dataframe to csv
final_df.to_csv(config.final_df_path, index=False)

In [11]:
final_df.head()

,Elevation,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Horizontal_Distance_To_Fire_Points,Cover_Type
0,2991,7,67,11,1015,233,234,1570,1
1,2876,18,485,71,2495,192,202,1557,1
2,3171,2,277,9,4374,213,237,1052,0
3,3087,13,190,31,4774,193,221,752,0
4,2835,10,212,41,3596,231,242,3280,1

Nota: Se debe tener cargado el dataset (final_df) en memoria, pues posteriormente se debe hacer una división para algunas pruebas.

**4. Data PipeLine

**4.1 Configurar el contexto interactivo

In [14]:
# Instala TFX (si aún no lo has hecho)
!pip install tfx

import os
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext

# Define la raíz del pipeline (por ejemplo, en una carpeta en el directorio actual)
pipeline_root = os.path.join(os.getcwd(), "tfx_pipeline_output")

# Crea el contexto interactivo
context = InteractiveContext(pipeline_root=str(pipeline_root))

# Verifica el directorio
print("Pipeline root:", pipeline_root)

Requirement already satisfied: tfx in /usr/local/lib/python3.9/site-packages (1.16.0)
Requirement already satisfied: ml-pipelines-sdk==1.16.0 in /usr/local/lib/python3.9/site-packages (from tfx) (1.16.0)
Requirement already satisfied: absl-py<2.0.0,>=0.9 in /usr/local/lib/python3.9/site-packages (from tfx) (1.4.0)
Requirement already satisfied: ml-metadata<1.17.0,>=1.16.0 in /usr/local/lib/python3.9/site-packages (from tfx) (1.16.0)
Requirement already satisfied: packaging>=22 in /usr/local/lib/python3.9/site-packages (from tfx) (24.2)
Requirement already satisfied: portpicker<2,>=1.3.1 in /usr/local/lib/python3.9/site-packages (from tfx) (1.6.0)
Requirement already satisfied: protobuf<5,>=3.20.3 in /usr/local/lib/python3.9/site-packages (from tfx) (3.20.3)
Requirement already satisfied: docker<8,>=7 in /usr/local/lib/python3.9/site-packages (from tfx) (7.1.0)
Requirement already satisfied: google-apitools<1,>=0.5 in /usr/local/lib/python3.9/site-packages (from tfx) (0.5.31)
Requirement already satisfied: google-api-python-client<2,>=1.8 in /usr/local/lib/python3.9/site-packages (from tfx) (1.12.11)
Requirement already satisfied: jinja2<4,>=2.7.3 in /usr/local/lib/python3.9/site-packages (from tfx) (3.1.5)
Requirement already satisfied: typing-extensions<5 in /usr/local/lib/python3.9/site-packages (from tfx) (4.12.2)
Requirement already satisfied: apache-beam<3,>=2.47 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.63.0)
Requirement already satisfied: attrs<24,>=19.3.0 in /usr/local/lib/python3.9/site-packages (from tfx) (23.2.0)
Requirement already satisfied: click<9,>=7 in /usr/local/lib/python3.9/site-packages (from tfx) (8.1.8)
Requirement already satisfied: google-api-core<3 in /usr/local/lib/python3.9/site-packages (from tfx) (2.24.1)
Requirement already satisfied: google-cloud-aiplatform<2,>=1.6.2 in /usr/local/lib/python3.9/site-packages (from tfx) (1.82.0)
Requirement already satisfied: google-cloud-bigquery<4,>=3 in /usr/local/lib/python3.9/site-packages (from tfx) (3.29.0)
Requirement already satisfied: grpcio<2,>=1.28.1 in /usr/local/lib/python3.9/site-packages (from tfx) (1.65.5)
Requirement already satisfied: keras-tuner!=1.4.0,!=1.4.1,<2,>=1.0.4 in /usr/local/lib/python3.9/site-packages (from tfx) (1.4.7)
Requirement already satisfied: kubernetes<27,>=10.0.1 in /usr/local/lib/python3.9/site-packages (from tfx) (26.1.0)
Requirement already satisfied: numpy<2,>=1.16 in /usr/local/lib/python3.9/site-packages (from tfx) (1.26.4)
Requirement already satisfied: pyarrow<11,>=10 in /usr/local/lib/python3.9/site-packages (from tfx) (10.0.1)
Requirement already satisfied: orjson!=3.10.7 in /usr/local/lib/python3.9/site-packages (from tfx) (3.10.15)
Requirement already satisfied: scipy<1.13 in /usr/local/lib/python3.9/site-packages (from tfx) (1.12.0)
Requirement already satisfied: scikit-learn==1.5.1 in /usr/local/lib/python3.9/site-packages (from tfx) (1.5.1)
Requirement already satisfied: pyyaml<7,>=6 in /usr/local/lib/python3.9/site-packages (from tfx) (6.0.2)
Requirement already satisfied: tensorflow<2.17,>=2.16.0 in /usr/local/lib/python3.9/site-packages (from tfx) (2.16.2)
Requirement already satisfied: tensorflow-hub<0.16,>=0.15.0 in /usr/local/lib/python3.9/site-packages (from tfx) (0.15.0)
Requirement already satisfied: tensorflow-data-validation<1.17.0,>=1.16.1 in /usr/local/lib/python3.9/site-packages (from tfx) (1.16.1)
Requirement already satisfied: tensorflow-model-analysis<0.48.0,>=0.47.0 in /usr/local/lib/python3.9/site-packages (from tfx) (0.47.1)
Requirement already satisfied: tensorflow-serving-api<2.17,>=2.16 in /usr/local/lib/python3.9/site-packages (from tfx) (2.16.1)
Requirement already satisfied: tensorflow-transform<1.17.0,>=1.16.0 in /usr/local/lib/python3.9/site-packages (from tfx) (1.16.0)
Requirement already satisfied: tfx-bsl<1.17.0,>=1.16.1 in /usr/local/lib/python3.9/site-packages (from tfx) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.9/site-packages (from scikit-learn==1.5.1->tfx) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.9/site-packages (from scikit-learn==1.5.1->tfx) (3.5.0)
Requirement already satisfied: crcmod<2.0,>=1.7 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (1.7)
Requirement already satisfied: dill<0.3.2,>=0.3.1.1 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.3.1.1)
Requirement already satisfied: cloudpickle~=2.2.1 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2.2.1)
Requirement already satisfied: fastavro<2,>=0.23.6 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (1.10.0)
Requirement already satisfied: fasteners<1.0,>=0.3 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.19)
Requirement already satisfied: hdfs<3.0.0,>=2.1.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2.7.3)
Requirement already satisfied: httplib2<0.23.0,>=0.8 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.22.0)
Requirement already satisfied: jsonschema<5.0.0,>=4.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (4.23.0)
Requirement already satisfied: jsonpickle<4.0.0,>=3.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (3.4.2)
Requirement already satisfied: objsize<0.8.0,>=0.6.1 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.7.1)
Requirement already satisfied: pymongo<5.0.0,>=3.8.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (4.11.1)
Requirement already satisfied: proto-plus<2,>=1.7.1 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (1.26.0)
Requirement already satisfied: pydot<2,>=1.2.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (1.4.2)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2.9.0.post0)
Requirement already satisfied: pytz>=2018.3 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2025.1)
Requirement already satisfied: redis<6,>=5.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (5.2.1)
Requirement already satisfied: regex>=2020.6.8 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2024.11.6)
Requirement already satisfied: requests<3.0.0,>=2.24.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2.32.3)
Requirement already satisfied: sortedcontainers>=2.4.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (2.4.0)
Requirement already satisfied: zstandard<1,>=0.18.0 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.23.0)
Requirement already satisfied: pyarrow-hotfix<1 in /usr/local/lib/python3.9/site-packages (from apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.6)
Requirement already satisfied: cachetools<6,>=3.1.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (5.5.2)
Requirement already satisfied: google-auth<3,>=1.18.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.38.0)
Requirement already satisfied: google-auth-httplib2<0.3.0,>=0.1.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (0.2.0)
Requirement already satisfied: google-cloud-datastore<3,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.20.2)
Requirement already satisfied: google-cloud-pubsub<3,>=2.1.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.28.0)
Requirement already satisfied: google-cloud-pubsublite<2,>=1.2.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (1.12.0)
Requirement already satisfied: google-cloud-storage<3,>=2.18.2 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.19.0)
Requirement already satisfied: google-cloud-bigquery-storage<3,>=2.6.3 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.28.0)
Requirement already satisfied: google-cloud-core<3,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.4.2)
Requirement already satisfied: google-cloud-bigtable<3,>=2.19.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.29.0)
Requirement already satisfied: google-cloud-spanner<4,>=3.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (3.52.0)
Requirement already satisfied: google-cloud-dlp<4,>=3.0.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (3.28.0)
Requirement already satisfied: google-cloud-language<3,>=2.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.17.0)
Requirement already satisfied: google-cloud-videointelligence<3,>=2.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (2.16.0)
Requirement already satisfied: google-cloud-vision<4,>=2 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (3.10.0)
Requirement already satisfied: google-cloud-recommendations-ai<0.11.0,>=0.1.0 in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (0.10.16)
Requirement already satisfied: keyrings.google-artifactregistry-auth in /usr/local/lib/python3.9/site-packages (from apache-beam[gcp]<3,>=2.47->tfx) (1.1.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.9/site-packages (from docker<8,>=7->tfx) (2.3.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.9/site-packages (from google-api-core<3->tfx) (1.68.0)
Requirement already satisfied: six<2dev,>=1.13.0 in /usr/local/lib/python3.9/site-packages (from google-api-python-client<2,>=1.8->tfx) (1.17.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python3.9/site-packages (from google-api-python-client<2,>=1.8->tfx) (3.0.1)
Requirement already satisfied: oauth2client>=1.4.12 in /usr/local/lib/python3.9/site-packages (from google-apitools<1,>=0.5->tfx) (4.1.3)
Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /usr/local/lib/python3.9/site-packages (from google-cloud-aiplatform<2,>=1.6.2->tfx) (1.14.1)
Requirement already satisfied: shapely<3.0.0dev in /usr/local/lib/python3.9/site-packages (from google-cloud-aiplatform<2,>=1.6.2->tfx) (2.0.7)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.9/site-packages (from google-cloud-aiplatform<2,>=1.6.2->tfx) (2.10.6)
Requirement already satisfied: docstring-parser<1 in /usr/local/lib/python3.9/site-packages (from google-cloud-aiplatform<2,>=1.6.2->tfx) (0.16)
Requirement already satisfied: google-resumable-media<3.0dev,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery<4,>=3->tfx) (2.7.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/site-packages (from jinja2<4,>=2.7.3->tfx) (3.0.2)
Requirement already satisfied: keras in /usr/local/lib/python3.9/site-packages (from keras-tuner!=1.4.0,!=1.4.1,<2,>=1.0.4->tfx) (3.8.0)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.9/site-packages (from keras-tuner!=1.4.0,!=1.4.1,<2,>=1.0.4->tfx) (1.0.5)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.9/site-packages (from kubernetes<27,>=10.0.1->tfx) (2025.1.31)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.9/site-packages (from kubernetes<27,>=10.0.1->tfx) (58.1.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.9/site-packages (from kubernetes<27,>=10.0.1->tfx) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.9/site-packages (from kubernetes<27,>=10.0.1->tfx) (2.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/site-packages (from portpicker<2,>=1.3.1->tfx) (7.0.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (3.13.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.3.1 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (0.3.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (3.4.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (2.5.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (1.17.2)
Requirement already satisfied: tensorboard<2.17,>=2.16 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (2.16.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.9/site-packages (from tensorflow<2.17,>=2.16.0->tfx) (0.37.1)
Requirement already satisfied: pandas<2,>=1.0 in /usr/local/lib/python3.9/site-packages (from tensorflow-data-validation<1.17.0,>=1.16.1->tfx) (1.5.3)
Requirement already satisfied: pyfarmhash<0.4,>=0.2.2 in /usr/local/lib/python3.9/site-packages (from tensorflow-data-validation<1.17.0,>=1.16.1->tfx) (0.3.2)
Requirement already satisfied: tensorflow-metadata<1.17,>=1.16.0 in /usr/local/lib/python3.9/site-packages (from tensorflow-data-validation<1.17.0,>=1.16.1->tfx) (1.16.1)
Requirement already satisfied: ipython<8,>=7 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (7.34.0)
Requirement already satisfied: ipywidgets<8,>=7 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (7.8.5)
Requirement already satisfied: pillow>=9.4.0 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (11.1.0)
Requirement already satisfied: rouge-score<2,>=0.1.2 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (0.1.2)
Requirement already satisfied: sacrebleu<4,>=2.3 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (2.5.1)
Requirement already satisfied: tensorflow-estimator>=2.10 in /usr/local/lib/python3.9/site-packages (from tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (2.15.0)
Requirement already satisfied: tf-keras>=2 in /usr/local/lib/python3.9/site-packages (from tensorflow-transform<1.17.0,>=1.16.0->tfx) (2.16.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow<2.17,>=2.16.0->tfx) (0.45.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform<2,>=1.6.2->tfx) (1.49.0rc1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tfx) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]<3,>=2.47->tfx) (4.9)
Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigtable<3,>=2.19.0->apache-beam[gcp]<3,>=2.47->tfx) (0.14.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.47->tfx) (1.30.0)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-pubsub<3,>=2.1.0->apache-beam[gcp]<3,>=2.47->tfx) (1.30.0)
Requirement already satisfied: overrides<8.0.0,>=6.0.1 in /usr/local/lib/python3.9/site-packages (from google-cloud-pubsublite<2,>=1.2.0->apache-beam[gcp]<3,>=2.47->tfx) (7.7.0)
Requirement already satisfied: sqlparse>=0.4.4 in /usr/local/lib/python3.9/site-packages (from google-cloud-spanner<4,>=3.0.0->apache-beam[gcp]<3,>=2.47->tfx) (0.5.3)
Requirement already satisfied: grpc-interceptor>=0.15.4 in /usr/local/lib/python3.9/site-packages (from google-cloud-spanner<4,>=3.0.0->apache-beam[gcp]<3,>=2.47->tfx) (0.15.4)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-storage<3,>=2.18.2->apache-beam[gcp]<3,>=2.47->tfx) (1.6.0)
Requirement already satisfied: docopt in /usr/local/lib/python3.9/site-packages (from hdfs<3.0.0,>=2.1.0->apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (0.6.2)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.9/site-packages (from httplib2<0.23.0,>=0.8->apache-beam<3,>=2.47->apache-beam[gcp]<3,>=2.47->tfx) (3.2.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (5.2.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (5.14.3)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (3.0.50)
Requirement already satisfied: pygments in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (2.19.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.9/site-packages (from ipython<8,>=7->tensorflow-model-analysis<0.48.0,>=0.47.0->tfx) (4.9.0)

WARNING:absl:InteractiveContext metadata_connection_config not provided: using SQLite ML Metadata database at /home/jovyan/work/tfx_pipeline_output/metadata.sqlite.

Pipeline root: /home/jovyan/work/tfx_pipeline_output

**Generando ejemplos

In [16]:
from tfx.components import CsvExampleGen
import os

# Define la ruta de tus datos (ajústala según corresponda)
data_root_prepro = os.path.join(os.getcwd(), "data", "preprocessed")

# Instancia CsvExampleGen usando la carpeta que contiene el dataset en formato CSV
example_gen = CsvExampleGen(input_base=str(data_root_prepro))

# Ejecuta el componente en el contexto interactivo (asumiendo que ya definiste 'context')
context.run(example_gen)

print("CsvExampleGen ok")

WARNING:apache_beam.runners.interactive.interactive_environment:Dependencies required for Interactive Beam PCollection visualization are not available, please use: `pip install apache-beam[interactive]` to install necessary dependencies to enable all data visualization features.

RuntimeError: Split pattern /home/jovyan/work/data/preprocessed/* does not match any files.

**4.3 Estadísticas

In [ ]:
# get the artifact object
artifact = example_gen.outputs('examples').get()[0]

# print split names and uri
print(f'split names: (artifact.split_names)')
print(f'artifact uri: (artifact.uri)')